cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings
app_name = "cart"

urlpatterns = [
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^cart_detail/$', views.cart_detail,name='cart_detail'),
]

exam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from shop import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^customer/', include('customers.urls')),
    url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^webpages/', include('webpages.urls', namespace="webpages")),
    url(r'^user/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from orders import views
app_name = 'orders'

urlpatterns = [
    url(r'^create/', views.order_create, name = 'order_create'),
]

orders/models.py
from django.db import models
from shop.models import Product
# Create your models here.

class Order(models.Model):
    first_name = models.CharField(max_length =50)
    last_name = models.CharField(max_length =50)
    email = models.EmailField()
    address = models.CharField(max_length =250)
    postal_code = models.CharField(max_length =20)
    city = models.CharField(max_length =100)
    created = models.DateTimeField(auto_now = True)
    updateted = models.DateTimeField(auto_now = True)
    paid = models.BooleanField(default = False)

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return 'Order{}'.format(self.id)
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.PROTECT)
    price = models.IntegerField()
    quantity = models.PositiveIntegerField(default = 1)
    def __str__(self):
        return '{}'.format(self.id)
    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from orders.models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email','address','postal_code','city']

orders/views.py
from django.shortcuts import render
from orders.models import OrderItem
from orders.forms import OrderCreateForm
from cart.cart import Cart
# Create your views here.
def order_create(request):
    cart = Cart(request)
    form = OrderCreateForm()
    if request.method == 'POST':
        print("I'm here")
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order = order,product = item['product'],price = item['fee'], quantity = item['quantity'])
            cart.clear()
            return render(request, 'orders/created.html', context = {'order' :order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/create.html',context={'form':form})

orders/templates/orders/create.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
<div class="container">
    <div class="row">
        <div class='col-md-6'>
            <form action="." method="post">
                <h2>THÔNG TIN KHÁCH HÀNG</h2>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputEmail4">First name</label>
                        <input class="form-control" type="text" name="first_name" maxlength="50" required="" id="id_first_name">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputPassword4">Last name</label>
                        <input class="form-control" type="text" name="last_name" maxlength="50" required="" id="id_last_name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail4">Email</label>
                    <input class="form-control" type="text" name="email" maxlength="50" required="" id="id_email">
                </div>
                <div class="form-group">
                    <label for="inputAddress">Address</label>
                    <input class="form-control" type="text" name="address" maxlength="50" required="" id="id_address">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputCity">City</label>
                        <input class="form-control" type="text" name="city" maxlength="50" required="" id="id_city">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputZip">Postal code</label>
                        <input class="form-control" type="text" name="postal_code" maxlength="50" required="" id="id_postal_code">
                    </div>
                </div>
                <button type="submit" value="Đặt hàng" class="btn btn-primary">Dat hang</button>
                {% csrf_token %}
            </form>

        </div>
        <div class='col-md-6'>

        </div>

    </div>
</div>

{% endblock %}

orders/templates/orders/created.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
    <h1>Đặt hàng thành công</h1>
    <p>Đơn đặt hàng của bạn đã đặt thành công. Mã đơn hàng
        <strong>{{order.id}}</strong></p>
</div>
{% endblock %}