cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings
app_name = "cart"

urlpatterns = [
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^cart_detail/$', views.cart_detail,name='cart_detail'),
]

customers/urls.py
from django.contrib import admin
from django.urls import path
from customers import views
from django.conf.urls import url
app_name = 'customers'

urlpatterns = [
    url(r'^dang_nhap/$', views.dang_nhap, name='dang_nhap'),
    url(r'^dang_ky/$', views.dang_ky, name='dang_ky'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'dang_xuat/$', views.dang_xuat, name = 'dang_xuat'),
]

exam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from shop import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^customer/', include('customers.urls')),
    url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^webpages/', include('webpages.urls', namespace="webpages")),
    url(r'^user/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    ho_ten = models.CharField(max_length = 60, blank = False)
    user_name = models.CharField(max_length = 100, blank = False)
    mat_khau = models.CharField(max_length = 100, blank = False)
    phone = models.CharField(max_length = 15, blank = False)
    email = models.CharField(max_length = 100, blank = False)
    dia_chi = models.CharField(max_length = 200, blank = False)
    def __str__(self):
        return self.ho_ten
    class Meta:
        db_table = u'Customer'

customers/forms.py
from django import forms
from customers.models import Customer

class FormSignin():
    user_name = forms.CharField(max_length = 50)
    mat_khau = forms.CharField(max_length = 50)

class CustomerCreate(forms.ModelForm):
    ho_ten = forms.CharField(max_length = 264)
    user_name = forms.CharField(max_length = 50)
    mat_khau = forms.CharField(widget = forms.PasswordInput())
    confirm = forms.CharField(widget = forms.PasswordInput())
    phone = forms.CharField(max_length = 15)
    email = forms.EmailField()
    dia_chi = forms.CharField(max_length = 200)
    class Meta:
        model = Customer
        fields = ['ho_ten', 'user_name', 'email','mat_khau','phone','dia_chi']

customers/views.py
from django.shortcuts import render
from customers.forms import CustomerCreate
from django.shortcuts import redirect
from customers.models import Customer
from django.contrib.auth.hashers import Argon2PasswordHasher

# Create your views here.
def dang_ky(request):
    form = CustomerCreate()
    registered = False
    if request.method == "POST":
        form = CustomerCreate(data=request.POST)
        hasher = Argon2PasswordHasher()
        if form.is_valid() and form.cleaned_data['mat_khau'] == form.cleaned_data['confirm']:
            request.POST._mutable = True
            register = form.save(commit=False)
            register.ho_ten = form.cleaned_data['ho_ten']
            register.user_name = form.cleaned_data['user_name']
            register.mat_khau = hasher.encode(form.cleaned_data['mat_khau'],'somewhere')
            register.email = form.cleaned_data['email']
            register.phone = form.cleaned_data['phone']
            register.dia_chi = form.cleaned_data['dia_chi']
            register.save()
            registered = True
            return render(request, 'customers/profile.html', {'username':register.user_name})
        elif form.cleaned_data['mat_khau'] != form.cleaned_data['confirm']:
            form.add_error('confirm', 'Mật khẩu không khớp')
        else:
           form = CustomerCreate()      
    return render(request, 'customers/dang_ky.html', {'form': form, 'registered': registered})

def dang_nhap(request):
    err = ''
    if request.session.has_key('username'):
        return redirect('customers:profile')
    elif request.method == "POST":
        hashers = Argon2PasswordHasher()
        _ten = request.POST.get('user_name')
        _mat_khau = hashers.encode(request.POST.get('mat_khau'),'somewhere')
        kh = Customer.objects.filter(user_name = _ten, mat_khau = _mat_khau)
        if kh.count() > 0:
            request.session['username'] = kh[0].ho_ten
            return redirect('customers:profile')
        else:
            err = "thong tin dang nhap khong dung"
    return render(request, 'customers/dang_nhap.html', {'err': err})

def profile(request):
    profile = Customer.objects.get(ho_ten=request.session['username'])
    if request.session.has_key('username'):
        username = request.session['username']
        return render(request, 'customers/profile.html', {'username': username, 'profile': profile, 'title': 'Thông tin khách hàng'})
    else:
        return redirect('customers:dang_nhap')

def dang_xuat(request):
    if request.session.has_key('username'):
        del request.session['username']
    return redirect('customers:dang_nhap')

customers/templates/customers/dang_ky.html
{% extends "base.html" %}
{% block body_block %}
{% if registered %}
<h4>Bạn đã đăng ký thành công</h4>
{% else %}
<form action="." method="post" class = "register">
    <h4 style="text-align:center">ĐĂNG KÝ</h4>
    <div class="form-row">
        <label for="inputname">Họ tên</label>
            <input class="form-control" type="text" name="ho_ten" maxlength="50" required="" id="id_ho_ten">
    </div>
    <div class="form-row">
        <label for="inputEmail4">Email</label>
            <input class="form-control" type="text" name="email" maxlength="50" required="" id="id_email">
    </div>
    <div class="form-row">
        <label for="inputusername">Username</label>
            <input class="form-control" type="text" name="user_name" maxlength="50" required="" id="id_user_name">
    </div>
    <div class="form-row">
        <label for="inputpassword">Password</label>
            <input class="form-control" type="password" name="mat_khau" maxlength="50" required="" id="id_mat_khau">
    </div>
    <div class="form-row">
        <label for="inputpassword">Confirm </label>
            <input class="form-control" type="password" name="confirm" maxlength="50" required="" id="id_confirm">
            {% if form.confirm.errors %}
            <span style="color:red">{{form.confirm.errors}}</span>
            {% endif %}
    </div>
    <div class="form-row">
        <label for="inputPhone">Phone</label>
            <input class="form-control" type="number" name="phone" maxlength="50" required="" id="id_phone">
    </div>
    <div class="form-row">
        <label for="inputAddress">Address</label>
        <input class="form-control" type="text" name="dia_chi" maxlength="50" required="" id="id_dia_chi">
    </div>
    <div class="col-md-12 text-center" style="padding-top: 15px;">
        <button type="submit" value="register" class="btn btn-primary">Đăng ký</button>
    </div>
    {% csrf_token %}
</form>
{% endif %}
{% endblock %}

customers/templates/customers/dang_nhap.html
{% extends "base.html" %}
{% block body_block %}

{% if registered %}
<h6>Đăng ký thành công, vui lòng đăng nhập hệ thống</h6>
{% endif %}
<form class="form-signin" method="post">
    <h1 class="h3 mb-3 font-weight-normal" style="text-align: center;">Vui lòng nhập thông tin đăng nhập</h1>
    <div class="form-group">
        <label for="exampleInputUsername">Username</label>
        <input type="text" name="user_name" class="form-control" id="exampleInputUsername" aria-describedby="emailHelp"
            placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" name="mat_khau" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    {% csrf_token%}
    {{err}}
    {{request.session.username}}
    <div class="col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Sign in</button>
    </div>
</form>
{% endblock %}

customers/templates/customers/profile.html
{% extends "base.html" %}
{% block body_block %}

<h1>THÔNG TIN KHÁCH HÀNG</h1>
<h3>Họ tên: {{profile.ho_ten}}</h3>
<h3>Số điện thoại: {{profile.phone}}</h3>
<h3>Email: {{profile.email}}</h3>
<h3>Địa chỉ: {{profile.dia_chi}}</h3>

<a class="nav-link" href="{% url 'customers:dang_xuat' %}">Log out</a>
{% endblock %}