cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings
app_name = "cart"

urlpatterns = [
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^cart_detail/$', views.cart_detail,name='cart_detail'),
]

exam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from shop import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^customer/', include('customers.urls')),
    url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^webpages/', include('webpages.urls', namespace="webpages")),
    url(r'^user/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from users import views
app_name = 'user'

urlpatterns = [
    url(r'^register/$', views.register, name = 'register'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^login/$',views.user_login,name='login'),
]

orders/models.py
from django.db import models
from shop.models import Product
# Create your models here.

class Order(models.Model):
    first_name = models.CharField(max_length =50)
    last_name = models.CharField(max_length =50)
    email = models.EmailField()
    address = models.CharField(max_length =250)
    postal_code = models.CharField(max_length =20)
    city = models.CharField(max_length =100)
    created = models.DateTimeField(auto_now = True)
    updateted = models.DateTimeField(auto_now = True)
    paid = models.BooleanField(default = False)

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return 'Order{}'.format(self.id)
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.PROTECT)
    price = models.IntegerField()
    quantity = models.PositiveIntegerField(default = 1)
    def __str__(self):
        return '{}'.format(self.id)
    def get_cost(self):
        return self.price * self.quantity

users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    #create relationship from this class to User
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    #add any more attribute you want
    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to = "images/", blank=True)
    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from users.models import UserProfileInfo, User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('first_name','last_name','username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    porfolio = forms.URLField(required = False)
    picture = forms.ImageField(required = False)
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio','picture')

users/views.py
from django.shortcuts import render
from users import models
from users import forms

# Create your views here.
def register(request):
    registered = False
    if request.method == "POST":
        form_user = forms.UserForm(data = request.POST)
        form_por = forms.UserProfileInfoForm(data = request.POST)
        if form_user.is_valid() and form_por.is_valid():
            user = form_user.save()
            user.set_password(user.password)
            user.save()

            profile = form_por.save(commit = False)
            profile.user = user
            
            print(request.FILES)
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()
            registered = True
        else:
            print(form_user.errors, form_por.errors)
    else:
        form_user = forms.UserForm()
        form_por = forms.UserProfileInfoForm()
    return render(request, "users/registration.html", {'user_form':form_user,'profile_form': form_por, 'registered': registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password = password)
        if user.is_active:
            login(request, user)
            result = "Chào bạn " + username
            return render(request, "users/profile.html", {"result":result})
        else:
            print("Không đăng nhập được")
            print("Username: {} and password: {}".format(username, password))
            login_result = "Username và password không hợp lệ"
            return render(request, "users/login.html",{"login_result", login_result})
    else:
        return render(request, "users/login.html")


def user_logout(request):
    logout(request)
    result = "Bạn đã đăng xuất. Vui lòng chọn 'Đăng nhập'"
    return render(request, "users/profile.html", {"result":result})

users/templates/users/login.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
<div class="container">
    <h1>Đăng nhập</h1>
    <form method="POST" action="{% url 'user:login' %}">
        <table>
            <tr>
                <td>
                    <lable for="username">Username:</lable>
                </td>
                <td><input type="text" name="username" placeholder="Enter username">

                </td>
            </tr>
            <tr>
                <td>
                    <lable for="password">Password:</lable>
                </td>
                <td><input type="password" name="password" placeholder="Enter password"></td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" class="btn btn-primary" value="Submit">
                </td>
            </tr>
        </table>
        {% csrf_token %}
    </form>
</div>
<div class="container">
    <font color="red"></font>{{login_result}}</font>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="container">
    {% if registered %}
    <h3>Bạn đã đăng ký thành công.</h3>
    {% else %}
    <form method="POST" class="register" enctype="multipart/form-data">
        <h4 style="text-align:center">Đăng ký người dùng</h4>
        <div class="form-row">
            <label for="inputname">First Name</label>
            <input class="form-control" type="text" name="first_name" maxlength="50" required="" id="id_first_name">
        </div>
        <div class="form-row">
            <label for="inputname">Last Name</label>
            <input class="form-control" type="text" name="last_name" maxlength="50" required="" id="id_last_name">
        </div>
        <div class="form-row">
            <label for="inputname">Username</label>
            <input class="form-control" type="text" name="username" maxlength="50" required="" id="id_username">
        </div>
        <div class="form-row">
            <label for="inputEmail4">Email</label>
            <input class="form-control" type="text" name="email" maxlength="50" required="" id="id_email">
        </div>
        <div class="form-row">
            <label for="inputpassword">Password</label>
            <input class="form-control" type="password" name="password" maxlength="50" required="" id="id_password">

        </div>
        <div class="form-row">
            <label for="inputPhone">Portfolio</label>
            <input class="form-control" type="url" name="portfolio" maxlength="50" required="" id="id_portfolio">
        </div>
        <div class="form-row">
            <label for="exampleFormControlFile1">Picture profile</label>
            <input type="file" class="form-control-file" name="picture" id="id_picture">
        </div>
        {% csrf_token %}
        <button type="submit" value="register" class="btn btn-primary">Đăng ký</button>

        <!-- <table>
            {% for field in user_form %}
            <tr>
                <td>{{field.label}} </td>
                <td>{{field}}</td>
            </tr>
            {% endfor %}
            {% for field1 in profile_form %}
            <tr>
                <td>{{field1.label}} </td>
                <td>{{field1}}</td>
            </tr>
            {% endfor %}
            {% csrf_token %}
            <tr>
                <td colspan='2' align="center">
                    <input type="submit" class="btn btn-primary" value="Đăng ký">
                </td>
            </tr>
        </table> -->
    </form>
    {% endif %}
</div>
</div>
{% endblock %}