cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings
app_name = "cart"

urlpatterns = [
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^cart_detail/$', views.cart_detail,name='cart_detail'),
]

customers/urls.py
from django.contrib import admin
from django.urls import path
from customers import views
from django.conf.urls import url
app_name = 'customers'

urlpatterns = [
    url(r'^dang_nhap/$', views.dang_nhap, name='dang_nhap'),
    url(r'^dang_ky/$', views.dang_ky, name='dang_ky'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'dang_xuat/$', views.dang_xuat, name = 'dang_xuat'),
]

exam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from shop import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^customer/', include('customers.urls')),
    url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^webpages/', include('webpages.urls', namespace="webpages")),
    url(r'^user/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
from django.conf.urls import url
app_name = 'shop'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^product_detail/(\d+)/$', views.product_detail, name='product_detail'),
    url(r'^product/$', views.product, name='product'),
]

webpages/urls.py
from django.contrib import admin
from django.urls import path
from webpages import views
from django.conf.urls import url
app_name = 'webpage'

urlpatterns = [
    url(r'^gioithieu/$', views.blog_detail, name='gioithieu'),
    url(r'^giaohang/$', views.blog, name='giaohang'),
    url(r'^contact/$', views.contact, name='contact'),
]

templates/base.html
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">

  <title>SHOP</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'shop:index' %}" style="background-image: url({% static 'images/logo.png' %}); background-repeat: no-repeat"></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'shop:index' %}">TRANG CHỦ <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:product' %}">SẢN PHẨM</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'webpage:giaohang' %}">GIAO HÀNG</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webpage:gioithieu' %}">GIỚI THIỆU</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'webpage:contact' %}">LIÊN HỆ</a>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto navright">
        {% if request.session.username %}
        <p class="navtext">Hi, {{request.session.username}}</p>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'customers:dang_nhap' %}">ĐĂNG NHẬP<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customers:dang_ky' %}">ĐĂNG KÝ</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link navcart" href="{% url 'cart:cart_detail'%}" style="background-image: url({% static 'images/cart.png' %}); background-repeat: no-repeat"></a>
        </li>
        <li class="nav-item navtext">
          {% if cart %}
          <a class="nav-link" href="{% url 'cart:cart_detail'%}">
            Giỏ hàng có {{cart|length}} sản phẩm , VNĐ: {{cart.get_total_fee}}</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block breadcrumbs %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'shop:index' %}">Trang chủ</a></li>
        {% block crumbs %}
        {% if title %} &rsaquo; {{ title }}{% endif %}
        {% endblock %}
      </ol>
    </nav>
    {% endblock %}
  </div>
  <div class="container">
      {% block body_block %}

      {% endblock %}
  </div>
  

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://blackrockdigital.github.io/startbootstrap-half-slider/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</body>
</html>